### ISSUE TITLE
Can't PM the bot

### ISSUE THREAD

**Issue by lilithlavender** [michaeljacobdavis/hubot-slack-whitelist-middleware#1]
When the whitelist is enabled the bot doesn't respond to commands sent in a private message (in slack). Need a way to whitelist private messages.

**Comment by lilithlavender** [comment]
Apparently this is a failure of hubot-slack, and not a result of the whitelist.

**Comment by lilithlavender** [comment]
This is apparently [not an issue with hubot-slack](https://github.com/slackhq/hubot-slack/issues/214#issuecomment-229454387), and will need to be fixed through the middleware.

**Comment by michaeljacobdavis** [comment]
I'll take a look and see if it's possible to derive if a message event is a DM.

**Comment by lilithlavender** [comment]
I discovered that someone used your addon as a starting point to build https://www.npmjs.com/package/hubot-slack-blacklist-middleware, which accomplishes a similar goal while allowing PMs.
