### ISSUE TITLE
How to allow private commands?

### ISSUE THREAD

**Issue by coliver** [michaeljacobdavis/hubot-slack-whitelist-middleware#2]
Hi there. We have a huge team in slack and our bot sometimes says things in general that she shouldn't, so thank you for this. 

I just had the above question. Adding channels to the white list is working, but now private commands sent to the bot are ignored. I tried adding her name as a channel, but no dice.

**Comment by coliver** [comment]
I answered my own question after a bit of digging.  In slack, if the room name is equal to the user.name then it is a direct message.

**Comment by eh-am** [comment]
I don't know when this changed, but it seems the Channel is now "DM" (from my hubot):

```DEBUG Received message: 'bot test' in channel: DM, from: eduardo```

(Just in case someone stumbles upon this)
